# Generated by Django 4.0.3 on 2022-04-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('Cost_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Rent', models.FloatField()),
                ('Utilities', models.FloatField()),
                ('Inventory_Expenses', models.FloatField()),
                ('Total_Costs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Type', models.CharField(max_length=40)),
                ('Dining_Environment', models.CharField(max_length=40)),
                ('Number_Total_Employees', models.IntegerField()),
                ('Cuisine', models.CharField(max_length=40)),
                ('Max_Capacity', models.IntegerField()),
                ('Meal_Type', models.CharField(max_length=40)),
                ('Rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Rewards_Program',
            fields=[
                ('Customer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=40)),
                ('Program_Name', models.CharField(max_length=40)),
                ('Total_Points', models.FloatField()),
                ('Cumulative_Points_Used', models.IntegerField(default=0)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Location_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Town', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=40)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('Financial_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Revenue_Per_Month', models.FloatField()),
                ('Costs_Per_Month', models.FloatField()),
                ('Net_Profit_Per_Month', models.FloatField()),
                ('Cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum.cost')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Job_Type', models.CharField(max_length=40)),
                ('Hourly_Salary', models.FloatField()),
                ('Weekly_Hours', models.FloatField()),
                ('Satisfaction', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum.restaurant')),
            ],
        ),
    ]
