# Generated by Django 4.0.3 on 2022-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='Total_Salaries',
            field=models.FloatField(default=0),
        ),
    ]
